// Package headername provides constants for HTTP header names.
package headername

const (
	Accept              = "Accept"
	AcceptCharset       = "Accept-Charset"
	AcceptEncoding      = "Accept-Encoding" // AcceptEncoding is handled effectively by net/http and can be disregarded here
	AcceptLanguage      = "Accept-Language"
	Allow               = "Allow"
	Authorization       = "Authorization"
	CacheControl        = "Cache-Control"
	ContentDisposition  = "Content-Disposition"
	ContentEncoding     = "Content-Encoding"
	ContentLanguage     = "Content-Language"
	ContentLength       = "Content-Length"
	ContentType         = "Content-Type"
	Cookie              = "Cookie"
	ETag                = "ETag"
	Expires             = "Expires"
	SetCookie           = "Set-Cookie"
	IfModifiedSince     = "If-Modified-Since"
	IfNoneMatch         = "If-None-Match"
	LastModified        = "Last-Modified"
	Location            = "Location"
	Pragma              = "Pragma"
	Upgrade             = "Upgrade"
	Vary                = "Vary"
	WWWAuthenticate     = "WWW-Authenticate"
	XForwardedFor       = "X-Forwarded-For"
	XForwardedProto     = "X-Forwarded-Proto"
	XForwardedProtocol  = "X-Forwarded-Protocol"
	XForwardedSsl       = "X-Forwarded-Ssl"
	XUrlScheme          = "X-Url-Scheme"
	XHTTPMethodOverride = "X-HTTP-Method-Override"
	XRealIP             = "X-Real-IP"
	XRequestID          = "X-Request-ID"
	XCorrelationID      = "X-Correlation-ID"
	XRequestedWith      = "X-Requested-With" // XRequestedWith defines the header strings used for XHR.
	Server              = "Server"
	Origin              = "Origin"
)
